name: CI - kroxai-mini

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.10, 3.11]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ matrix.python-version }}-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-${{ matrix.python-version }}-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then python -m pip install -r requirements.txt; fi

      - name: Syntax check (compile)
        run: |
          python -m py_compile scripts/wikidict_importer.py || true
          python -m py_compile api.py || true
          python -m py_compile kroxai/server.py || true
          python -m py_compile kroxai/integrations/wikidict.py || true

      - name: Run tests (if present)
        run: |
          if [ -d tests ]; then python -m pip install pytest || true; pytest -q || true; fi

      - name: Lint (optional)
        run: |
          if python -c "import pkgutil; exit(0 if pkgutil.find_loader('flake8') else 1)"; then
            flake8 || true
          else
            echo "flake8 not installed; skipping lint"
          fi
